parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2015
  sourceType: module

env:
  node: true

plugins:
  - codegen
  - prettier

rules:
  codegen/codegen: error
  # codegen seems to get mad without prettier installed, but we don't actually use it
  prettier/prettier: off

overrides:
  - files: '*.ts'
    rules:
      no-undef: off
      no-unused-vars: off
      indent: ['error', 'tab']
      quotes: ['error', 'single']
      semi: ['error', 'always']
      object-curly-spacing: ['error', 'always']
      comma-dangle: ['error', 'always-multiline']
      eol-last: error
